grafana:
    adminUser: ""
    adminPassword: ""
    envFromSecret: "grafana-admin-secret"

    ingress:
        enabled: false

prometheus:
    prometheusSpec:
        # Découverte cross-namespace (surveille the-tip-top-api)
        podMonitorNamespaceSelector: { }
        serviceMonitorNamespaceSelector: { }
        podMonitorSelector: { }
        serviceMonitorSelector: { }

alertmanager:
    enabled: true

nodeExporter:
    enabled: true # métriques infra nœud

kubeStateMetrics:
    enabled: true  # métriques Kubernetes (pods, deployments...)

