api_platform:
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    docs_path: /api/docs
    title: Hello Thé Tip Top
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

