api_platform:
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    swagger:
        api_keys: [ ]
    enable_swagger_ui: false
    enable_re_doc: false
    title: Hello Thé Tip Top
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

