apiVersion: v1
kind: Service
metadata:
    name: mysqld-exporter
    namespace: the-tip-top-api
    labels:
        app: mysqld-exporter
spec:
    selector:
        app: mysqld-exporter
    ports:
        - port: 9104
          targetPort: 9104
          name: metrics
